ui/src/components/certimate/AccessEdit.tsx, ui/src/pages/dashboard/Dashboard.tsx, ui/tailwind.config.js
1.  修复首页控制面板在md和2xl的时候会超出屏幕
2.  修复授权管理-添加授权选择ssh 弹窗过长超出屏幕无法滚动
=> fix: 首页展示问题和授权管理弹窗无法滚动

internal/deployer/ssh.go, ui/package.json, ui/src/components/certimate/AccessSSHForm.tsx, ui/src/domain/access.ts
Close #72
在 `internal/deployer/ssh.go` 里，因为一个 session 只能使用一次 `session.Run`，想实现增加一个前置命令就只能再 New 个 session，我这里的写法我不太确定是否符合这个项目的风格，大佬轻喷（doge
=> feat: pre command for ssh deploy

internal/deployer/ssh.go
=> fix: wrong pre command reference

go.mod, go.sum, internal/deployer/tencent_cdn.go
=> add feat: support for tencent cdn extensive domain

ui/src/components/certimate/Version.tsx, ui/src/pages/DashboardLayout.tsx, ui/src/pages/LoginLayout.tsx
=> Document location adjustment

internal/deployer/aliyun_esa.go
issue: https://github.com/usual2970/certimate/issues/223
@usual2970 TBR;
=> fix: handle aliyun dcdn does not support wildcard domain #223

internal/applicant/applicant.go, internal/domain/domains.go, ui/src/components/ui/tooltip.tsx, ui/src/domain/domain.ts, ui/src/i18n/locales/en/nls.domain.json, ui/src/i18n/locales/zh/nls.domain.json, ui/src/pages/domains/Edit.tsx
@usual2970 TBR;
相关 issue: #228
=> feat: 支持配置 CNAME 认证跟随禁用

internal/deployer/qiniu_cdn.go, internal/domain/domains.go
=> Qiniu cdn supports wildcard domain deployment

internal/deployer/k8s_secret.go
支持当secret不存在的时候可以创建，添加annotations，简化客户端连接。添加了secret type。
解决了#226 。
=> Support create secret, add cert annotations.

internal/domain/notify.go, internal/notify/notify.go, ui/src/components/notify/ServerChan.tsx, ui/src/domain/settings.ts, ui/src/i18n/locales/en/nls.common.json, ui/src/i18n/locales/en/nls.settings.json, ui/src/i18n/locales/zh/nls.common.json, ui/src/i18n/locales/zh/nls.settings.json, ui/src/pages/setting/Notify.tsx
- 新增Server酱通知
-----
实际上是一个客制化的Webhook，但是由于请求的参数和方式需要特制所以单独分了出来。
=> feat: add ServerChan notifier

internal/domain/notify.go, internal/notify/mail.go, internal/notify/notify.go, ui/src/components/notify/Mail.tsx, ui/src/domain/settings.ts, ui/src/i18n/locales/en/nls.common.json, ui/src/i18n/locales/en/nls.settings.json, ui/src/i18n/locales/zh/nls.common.json, ui/src/i18n/locales/zh/nls.settings.json, ui/src/pages/setting/Notify.tsx
=> feat: add mail push

internal/deployer/k8s_secret.go
=> fix: k8s部署更新报错

ui/src/components/certimate/DeployToLocal.tsx, ui/src/i18n/locales/en/nls.domain.json, ui/src/i18n/locales/zh/nls.domain.json
=> feat: add netsh preset

internal/domain/notify.go, internal/notify/notify.go, ui/src/components/notify/Bark.tsx, ui/src/domain/settings.ts, ui/src/i18n/locales/en/nls.common.json, ui/src/i18n/locales/en/nls.settings.json, ui/src/i18n/locales/zh/nls.common.json, ui/src/i18n/locales/zh/nls.settings.json, ui/src/pages/setting/Notify.tsx
- 加入了 Bark 通知服务
界面预览：
配置界面：
使用默认服务器：
自定义服务器：
收到通知：
=> feat: add Bark notifier

internal/notify/mail.go, internal/notify/notify.go
=> fix: resolve email notification delivery failure

internal/pkg/vendors/dogecloud-sdk/client.go
该 PR 包含以下内容变更：
- **fix**: 关闭 #303
=> bugfix #303

internal/pkg/core/uploader/providers/dogecloud/dogecloud.go
该 PR 包含以下内容变更：
- **fix**: 关闭 #308
=> bugfix #308

internal/pkg/vendors/qiniu-sdk/models.go
该 PR 包含以下内容变更：
- **fix**: 关闭 #304
=> bugfix #304

internal/deployer/aliyun_alb.go, internal/deployer/aliyun_nlb.go, internal/deployer/tencent_clb.go
该 PR 包含以下内容变更：
- **fix**: 关闭 #318
=> bugfix #318

ui/src/components/certimate/DeployToTencentCLB.tsx
该 PR 包含以下内容变更：
- **fix**: 关闭 #324。
=> bugfix #324

internal/deployer/aliyun_clb.go, internal/pkg/core/uploader/providers/aliyun-slb/aliyun_slb.go
该 PR 包含以下内容的变更：
- **fix**: 关闭 #326。
=> bugfix #326

internal/deployer/qiniu_cdn.go
该 PR 包含以下内容变更：
- **fix**: 关闭 #330。
=> bugfix #330

internal/deployer/aliyun_clb.go, internal/pkg/core/uploader/providers/aliyun-slb/aliyun_slb.go
该 PR 包含以下内容变更：
- **fix**: 修复两处 switch-case 多路分支匹配语法问题，可能导致阿里云金融云地域下的 CLB 部署失败。
=> fix switch-case syntax error

README.md, README_EN.md, internal/deployer/deployer.go, internal/deployer/volcengine_cdn.go, internal/deployer/volcengine_live.go, internal/pkg/core/uploader/providers/volcengine-cdn/volcengine_cdn.go, ui/src/components/certimate/DeployEditDialog.tsx, ui/src/components/certimate/DeployToVolcengineCDN.tsx, ui/src/domain/domain.ts, ui/src/i18n/locales/en/nls.common.json, ui/src/i18n/locales/zh/nls.common.json
=> feat: add volcengine cdn deployer

internal/pkg/vendors/huaweicloud-cdn-sdk/client.go
该 PR 包含以下内容变更：
- **fix**: 关闭 #361。
=> bugfix #361

internal/deployer/providers.go, internal/domain/provider.go, internal/pkg/core/deployer/providers/tencentcloud-cdn/tencentcloud_cdn.go, internal/pkg/core/deployer/providers/tencentcloud-ecdn/tencentcloud_ecdn.go, ui/src/components/workflow/node/ApplyNodeConfigForm.tsx, ui/src/components/workflow/node/DeployNodeConfigFormAliyunCDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormAliyunDCDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormAliyunOSSConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormBaiduCloudCDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormBytePlusCDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormQiniuCDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormTencentCloudCDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormTencentCloudCLBConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormTencentCloudECDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormVolcEngineCDNConfig.tsx, ui/src/components/workflow/node/DeployNodeConfigFormVolcEngineLiveConfig.tsx, ui/src/utils/validators.ts
该 PR 包含以下内容变更：
- **fix**: 关闭 #405
=> bugfix #405 on v0.3.x

internal/deployer/tencent_teo.go, ui/src/components/certimate/DeployToTencentTEO.tsx
该 PR 包含以下内容变更：
- **fix**: 关闭 #367
=> bugfix #367 on v0.2.x

internal/certificate/service.go, internal/domain/dtos/certificate.go, internal/domain/workflow.go, internal/rest/handlers/certificate.go, internal/workflow/node-processor/processor.go, internal/workflow/node-processor/upload_node.go, ui/src/api/certificates.ts, ui/src/components/workflow/WorkflowElement.tsx, ui/src/components/workflow/node/AddNode.tsx, ui/src/components/workflow/node/UploadNode.tsx, ui/src/components/workflow/node/UploadNodeConfigForm.tsx, ui/src/domain/workflow.ts, ui/src/i18n/locales/en/nls.workflow.nodes.json, ui/src/i18n/locales/zh/nls.workflow.nodes.json
=> add upload certificate node

internal/pkg/core/deployer/providers/k8s-secret/k8s_secret.go
=> fix: k8s secret not updated

migrations/1740050400_collections_hotfix.go, ui/src/components/workflow/node/UploadNodeConfigForm.tsx
该 PR 包含以下内容的变更：
- **fix**: 修复部分场景下字段长度溢出的问题。关闭 #458
=> bugfix #458

.github/workflows/push_image.yml
=> 镜像增加大版本 tag

ui/src/components/workflow/WorkflowElements.tsx
=> 解决分支过多内容展示不完整的问题

internal/pkg/core/deployer/providers/baishan-cdn/baishan_cdn.go, internal/pkg/vendors/baishan-sdk/models.go
fix: https://github.com/usual2970/certimate/issues/530
=> 修复白山云API 400209错误

internal/pkg/core/uploader/providers/volcengine-certcenter/volcengine_certcenter.go
=> 修复火山云证书上传获取空值的bug

internal/pkg/core/deployer/providers/gcore-cdn/gcore_cdn.go
该 PR 包含以下内容变更：
- **fix**: 关闭 #672
=> bugfix #672

internal/pkg/sdk3rd/wangsu/certificate/api.go
correct wangsu get certificate list api url
=> fix: wangsu get certificate list api error #741

internal/workflow/node-processor/execute_failure_node.go, internal/workflow/node-processor/execute_success_node.go, internal/workflow/node-processor/start_node.go, ui/src/components/workflow/node/ExecuteResultNode.tsx, ui/src/components/workflow/node/UnknownNode.tsx, ui/src/components/workflow/node/_SharedNode.tsx, ui/src/domain/workflow.ts, ui/src/i18n/locales/en/nls.workflow.nodes.json, ui/src/i18n/locales/zh/nls.workflow.nodes.json, ui/src/stores/workflow/index.ts
该 PR 包含以下内容变更：
- **feat**: 支持复制工作流已有节点或分支。关闭 #481
=> Support duplicating workflow nodes or branches

.github/workflows/release.yml
该 PR 包含以下内容变更：
- **build**: 调整 GitHub Actions 脚本，保持和之前版本一致的可执行文件名输出，并包含 README、LICENSE、CHANGELOG。
=> build: keep release files as before

ui/src/components/workflow/node/ApplyNodeConfigForm.tsx, ui/src/stores/contact/index.ts
https://github.com/usual2970/certimate/issues/174
邮箱输入框支持清理按钮
TBR; @usual2970 @fudiwei
=> feat(ui): support deleting email input box auto-complete items #174

pkg/core/ssl-applicator/acme-dns01/providers/tencentcloud-eo/internal/lego.go
如题，原逻辑采用先查找再更新的方式，但如果需要签发同时包含example.com和*.example.com的证书，dns记录则会冲突，无法完成签发
=> fix: 腾讯云edgeone DNS不支持签发同时包含example.com和*.example.com的证书
